### ISSUE TITLE
Running the tests exactly once?

### ISSUE THREAD

**Issue by lvh** [bensu/doo#1]
First off, thanks a lot for doo; it's a fantastic tool :) While it works really well for development (since it watches and automatically runs the build), is there a way to get it to just run once, i.e. for CI?

**Comment by bensu** [comment]
I just published `[0.1.1-SNAPSHOT]` which includes an extra argument to the command line: `once`; details in the README. Please let me know how it works before we close this issue.

**Comment by lvh** [comment]
Works a charm! Thank you so much :)
