### ISSUE TITLE
`lein doo` by itself doesn't use defaults

### ISSUE THREAD

**Issue by Peeja** [bensu/doo#101]
We have our defaults set in our `project.clj`:

```clj
:doo {:build "dev-test"
      :alias {:default [:chrome]}
      :paths {:karma "./node_modules/karma/bin/karma"}}
```

but `lein doo` doesn't use them:

```
$ lein doo

doo - run cljs.test in any JS environment.

Usage:

  lein doo {js-env}

  lein doo {js-env} {build-id}

  lein doo {js-env} {build-id} {watch-mode}

  - js-env: slimer, phantom, node, chrome, firefox, or an alias like headless
  - build-id: any of the ids under the :cljsbuild map in your project.clj
  - watch-mode: either auto (default) or once


All arguments are optional provided there is a corresponding default
under :doo in the project.clj.
```

If I'm reading the code right, that's because [with no arguments, `doo` always displays the help text](https://github.com/bensu/doo/blob/master/plugin/src/leiningen/doo.clj#L195), regardless of whether there are default values available.

**Comment by bensu** [comment]
Hi @Peeja 

Sorry for the delay. You are right, there is an inconsistency between the docs and the behavior. It should be help only if there is no default `js-env`.

**Comment by Peeja** [comment]
Thanks!
