### ISSUE TITLE
Testing javascscript code with `doo`

### ISSUE THREAD

**Issue by viebel** [bensu/doo#111]
I'd like to test `javascript` code with `doo`.

The trick I thought about was to include the `javascript` file as a `:preamble`. Like this:

```clojure
(defproject js-test-in-cljs "0.0.1"
  :description "Test Javascript code in clojurescript"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.36"]] 
  :plugins [[lein-doo "0.1.6"]]
  :source-paths ["src"]
  :cljsbuild {:builds
              {:test
               {:source-paths ["src"]
                :compiler
                {:main "js-test-in-cljs.test.runner"
                 :preamble ["main.js"]
                 :optimizations :simple
                 :output-to "resources/public/test/js/testable.js"
                 :output-dir "resources/public/test/js"}}}}})
```

The problem is that `:preamble` is not supported in `:optimizations :none`. And it cause the auto build of `lein doo` to be a bit slow (around 7 seconds).

Is there a better way to include `javscript` file with `doo`?

**Comment by bensu** [comment]
Hi @viebel ,

Can you check if using `:foreign-libs` as explained in #25 solves your issue?

**Comment by viebel** [comment]
It works like a charm!

**Comment by bensu** [comment]
Great! I should document this then (#112)
