### ISSUE TITLE
Google closure classes not found?

### ISSUE THREAD

**Issue by acron0** [bensu/doo#115]
I'm using `goog.Uri.QueryData` to parse query parameters and when running

```
lein doo phantom test once
```
I get this error:
```
ERROR in (filters) (witan_viz/db.js:43:46)
simple filter =
expected: (= (db/get-filters (make-url "?filter=foo%3Dbar")) (f/Filter. nil "foo" "=" "bar"))
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'qd.get("filter")')]
```

Which suggests that `.get` isn't found on `qd` (QueryData). Code works fine in dev, just not in test. It's included as such:

```
(:import [goog.Uri QueryData])
```

**Comment by bensu** [comment]
Hi @acron0,

Is `qd` a Google Closure global or an instance of `QueryData` that you made from ClojureScript?

Do you mind providing an example with the most basic Google Closure you can find that would reproduce the error? If the Google Closure classes were not found, it would first fail whenever you construct a GC object, like `new google.Uri(args)` or `new google.Uri.QueryData(args)`

Thanks!

**Comment by acron0** [comment]
PEBCAK, sorry

**Comment by bensu** [comment]
No problem!
