### ISSUE TITLE
testable.js problem

### ISSUE THREAD

**Issue by agzam** [bensu/doo#117]
Can someone help me to get to the bottom of this?

Apparently I'm doing something wrong, can't figure out exactly what:

I have created a sample project here: https://github.com/agzam/try-doo-with-spec

I know this is much to ask,  I would be forever grateful if you help me.

- clone it, 
- start `lein repl`, 
- run `(start)` - it would start figwheel repl, 
- navigate to `localhost:3333` - and you should see "Rock 'n' roll!`

Now, 
- go to `project.clj`, 
- enable commented line on lein-doo. 
- start the repl, 
- run `start`. 
- go to `localhost:3333` - It would complain that it can't find: `http://localhost:3333/js/testable.js`

**Comment by agzam** [comment]
it's like doo is 'injecting' its own handler into the ring handler. I don't want that.

**Comment by bensu** [comment]
Are you trying to use use figwheel and doo on the same cljsbuild config?

**Comment by agzam** [comment]
`doo` adds something by default, namely it makes Figwheel's Ring handler to act differently. No matter what I do, I can't find a workaround. Look at this file https://github.com/agzam/try-doo-with-spec/blob/master/dev/user.clj This is similar to "sass watcher" script from Figwheel's wiki -https://github.com/bhauman/lein-figwheel/wiki/SASS-watcher. 

Whenever lein-doo's dependency added (either as a plugin or a lib) I can't navigate to home page anymore.

**Comment by bensu** [comment]
I can't reproduce the issue on OSX. With or without `[lein-doo "0.1.7" :exclusions [[org.clojure/clojurescript]]]` I see "Rock 'n' roll!" on `localhost:3333`.

What OS are you using? Would you mind cloning the repo again and testing the steps from scratch to see if it makes a difference?

**Comment by agzam** [comment]
I'm on OSX 10.11.6. lein --version reports:

    leiningen 2.7.1 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM
    
I removed `~/.m2`, `resources` and `target` folders. Run `lein deps -U` then `lein repl` then `(start)`. In every browser I see the same - that error.

**Comment by agzam** [comment]
@bensu Oh. wow! I have found the culprit.. Something that in my `~/.lein/profiles` borking it!

**Comment by agzam** [comment]
@bensu I have finally found what was giving me headaches. it turned out to be `https://github.com/zcaudate/vinyasa`, namely injecting `vinyasa.lein`. Huge thanks for helping me out. I was frustrated for not being able to use `doo` which seems to be most popular way of running Clojurescript tests nowadays.

**Comment by bensu** [comment]
I'm glad it worked out!

**Comment by levitanong** [comment]
I'm actually getting the same issue as @agzam now. And I've checked my ~/.lein/profiles and emptied it. Issue still persists T_T If I comment out `lein-doo`, I don't get the `testable.js` error. Any idea what could cause this?

**Comment by bensu** [comment]
Hi @levitanong,

Can you please open a new issue with a more detailed description of the error and a minimal project that reproduces it?
