### ISSUE TITLE
:js-env setting is ignored

### ISSUE THREAD

**Issue by ricardojmendez** [bensu/doo#119]
Setting the `:js-env` value on the `:doo` settings map seems to have no effect. When running `lein with-profile test doo` it still asks me to specify the environment.

Tried with both `:doo {:build "test" :js-env :phantom}` and `:doo {:build "test" :js-env "phantom"}`.

Using 0.1.6 for the plugin and 0.1.7 for the library.

**Comment by miikka** [comment]
With the current version of Doo (0.1.8), there's no `:js-env` setting. The default environment is set by creating an alias called `:default`:

```clojure
:doo {:build "test"
      :alias {:default [:phantomjs]}}
```
