### ISSUE TITLE
Allow multiple build profiles

### ISSUE THREAD

**Issue by gmp26** [bensu/doo#126]
It appears to be impossible to configure `doo` if your `project.clj` uses profiles. For example:
```clj
:doo {:build "test"}
:profiles 
   {:dev {:cljsbuild ...}
    :prod {:cljsbuild ...}
    :test {:cljsbuild ...}
 }
```

For example `lein doo phantom test once` throws 
```
Exception in thread "main" java.lang.AssertionError: Assert failed: The given build (test) was not found in these options: main
(not (empty? build))
        at leiningen.doo$find_by_id.invokeStatic(doo.clj:91)
```
because leiningen.doo project builds expects :cljsbuild at top level in project.clj.
```clj
(defn project->builds [project]
  (get-in project [:cljsbuild :builds]))
```

**Comment by gmp26** [comment]
Closing this as `lein with-profile test doo phantom test once` works.

**Comment by bensu** [comment]
@gmp26 I'm glad it worked!
