### ISSUE TITLE
symbol in project.clj causes ClassNotFoundException

### ISSUE THREAD

**Issue by vemv** [bensu/doo#133]
Hi!

I have my cljsbuild options like this:

`:compiler {:closure-defines {foo.common.env/env "dev"}}`

This seems normal lein syntax. `foo.common.env/env` is quoted (like everything else in project.clj) and it shouldn't be evaluated as a clojure/java class.

`lein repl` and `lein figwheel` accept it. However `lein doo` does not - it tries to evaluate foo.common.env/env, causing a ClassNotFoundException.

I can 'solve' the issue by quoting `{foo.common.env/env "dev"}` with a backtick, but:

* I shouldn't be doing that in the first place - it's normal lein syntax
* It causes the lein figwheel validator to complain. It expects a map, not a quoted map.

Could it be the case that doo is parsing project.clj (or cljsbuild opts) in its own way?

Cheers - Victor

**Comment by metametadata** [comment]
Maybe you could use string name instead of a symbol? E.g. this define is accepted by both `figwheel` and `doo`:

`:closure-defines {"app.defines.DEBUG" true}`

**Comment by miikka** [comment]
Should be fixed in `[lein-doo "0.1.9"]`.
