### ISSUE TITLE
PhantomJS soon abandonned

### ISSUE THREAD

**Issue by DjebbZ** [bensu/doo#135]
The only maintainer stepped down, stating that soon it will get replaced by Chrome headless. Just reporting the info.

https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNEhttps://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by martinklepsch** [comment]
Here are some notes on using headless Chrome with Karma https://github.com/karma-runner/karma/issues/2489

**Comment by vemv** [comment]
This is kind of a good thing, at least PhJS is not a moving target anymore and consequently doo should have at least one stable target.

**Comment by bensu** [comment]
Thanks for the heads up! Fixed with #136
