### ISSUE TITLE
Chromium headless

### ISSUE THREAD

**Issue by darkleaf** [bensu/doo#139]
How can I run tests with karma-chrome-launcher and [chromium headless](https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L316)?

**Comment by miikka** [comment]
Support for Headless Chromimum could be added with a pull request similar to #136 .

**Comment by bensu** [comment]
Closed, now with #136 merged. Thank you @ProjectFrank for putting together the PR and @miikka for merging and moving so many things along!
