### ISSUE TITLE
Fails on Clojure-Alpha20

### ISSUE THREAD

**Issue by flyboarder** [bensu/doo#146]
`TypeError: undefined is not an object (evaluating 'cljs.test.report')`

**Comment by metametadata** [comment]
Seems to still be an issue with `[org.clojure/clojure "1.9.0-beta1"]`.

**Comment by miikka** [comment]
ClojureScript does not yet work with 1.9.0-alpha20 and later. See [CLJS-2352](https://dev.clojure.org/jira/browse/CLJS-2352).

**Comment by miikka** [comment]
ClojureScript 1.9.946 has been released. I quickly tested doo with it and Clojure 1.9.0-beta1 and it seems to work. Thus I'm going to close this issue.

If I missed something, please reopen this issue with more information!
