### ISSUE TITLE
Deploy key missing from Circle

### ISSUE THREAD

**Issue by miikka** [bensu/doo#148]
The build at Circle [are failing](https://circleci.com/gh/bensu/doo/92) when checking out the code:

```
Checkout using deploy key: 25:8c:1d:6b:c9:9d:8a:66:69:a7:59:f4:d4:da:15:84

Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git command i returned 128: 
```

I guess this means that Circle's deploy key has been removed GitHub.

@bensu, could you go to [Circle's settings](https://circleci.com/gh/bensu/doo/edit#checkout) and click "Add deploy key"? I think that should make the builds work again.

**Comment by bensu** [comment]
I just did! Let me know if you need anything else
