### ISSUE TITLE
doo crashes with Clojure 1.9

### ISSUE THREAD

**Issue by Jarzka** [bensu/doo#159]
I noticed a problem when running frontend tests on my stylefy project:
https://github.com/Jarzka/stylefy

Clone the project and run the tests:
`lein do clean, doo phantom test`
=> Tests are successful.

However, if you change Clojure version to 1.9.0 and run the tests again:
`lein do clean, doo phantom test`
you get:
> TypeError: undefined is not an object (evaluating 'cljs.test.report')

We are also using doo in Finnish Transport Agency's massive Harja project (https://github.com/finnishtransportagency/harja). We are unable to upgrade to Clojure 1.9 because of the same doo crash. :)

**Comment by Jarzka** [comment]
I was able to run tests by upgrading both Clojure (1.9) and ClojureScript (1.9.946)

A warning is still printed though:

> WARNING: doo's init function was not set
#object[TypeError TypeError: undefined is not an object (evaluating 'process_exit.call')]
TypeError: undefined is not an object (evaluating 'process_exit.call')

**Comment by Jarzka** [comment]
After upgrading cljs-build I was able to successfully compile production build and run tests with doo.

**Comment by bensu** [comment]
Thanks for the report!
