### ISSUE TITLE
Clashes with React?

### ISSUE THREAD

**Issue by rmoehn** [bensu/doo#16]
I was a bit desperate, not finding much information about how to run tests with `cljs.test`. So I used the friendly `cemerick.cljs.test` until I came across your plugin and was quite happy. However, a setup very similar to my `cemerick.cljs.test` setup before gives me this error:

```
;; ======================================================================
;; Testing with Slimer:
Warning: Error unmounting:
Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.
[JavaScript Error: "Error: Invariant Violation: _registerComponent(...):
Target container is not a DOM element." {file: "…/resources/public/js/test/test-main.js" line: 20314}
```
It seems like there's some problem with React, even though the one test I have now uses only plain `clojure.core` functions.

As I said, testing with cemerick.cljs.test worked. And I could run the tests directly in my application with `run-tests`, which rules out incompatibilities between cljs.test and cemerick.cljs.test as the cause.

The relevant section of project.clj looks like this:

```
:cljsbuild
{:builds
 [{:id "test"
    :source-paths ["src/cljs" "test/cljs"]
    :compiler {:output-to "resources/public/js/test/test-main.js"
               :output-dir "resources/public/js/test"
               :main 'theatralia.t-runner
               :optimizations :whitespace}]}
```

Can you help?

**Comment by bensu** [comment]
Can you show me the test runner?

My guess is that in one of your files, you have a top level form that tries to render React components. If you use om:

```clj
(om/root top-component app-state {:target (.getElementById "i-dont-exist-in-slimer")})

```

For some reason, `cemerick.test` didn't pull that namespace in during compilation (maybe `cljsbuild` vs `cljs.build.api` behavior, or `cemerick.test/run-tests` vs `cljs.test/run-tests`), but now `doo` does. So, when it runs your script,

**Comment by rmoehn** [comment]
Thanks for the quick reply! The test runner looks like this:

```
(ns theatralia.t-runner
  (:require [doo.runner :include-macros true]
            theatralia.t-thomsky))

(doo.runner/doo-tests 'theatralia.t-thomsky)
```

I just saw that its file was in the wrong place, but that shouldn't be cause. Your diagnosis sounds spot-on. The render function is called at the top level indeed. I will try your solution next week.

**Comment by bensu** [comment]
The runner looks fine, as long as `theatralia.t-thomsky` doesn't pull in the render function. Come back if you run into any more trouble.

**Comment by rmoehn** [comment]
Sorry for leaving this open for a long time. I will get to trying it out eventually.

**Comment by rmoehn** [comment]
Yup, hiding the render function works. Thanks a lot!

**Comment by logaan** [comment]
I see this issue is closed but isn't the underlying issue still relevant? In an environment like phantomjs we should be able to call `(.-body js/document)` right?
