### ISSUE TITLE
Subprocess fail with phantom on centos 7

### ISSUE THREAD

**Issue by 0xbase12** [bensu/doo#161]
Way to reproduce:
```
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

# lein -v
Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

# phantomjs -v
2.1.1

# git clone https://github.com/bensu/doo.git
# cd doo/library
# lein install
# cd ../plugin
# lein install
# cd ../example

# lein doo phantom test once
;; ======================================================================
;; Testing with Phantom:

Fontconfig warning: ignoring UTF-8: not a valid region tag

Testing example.core-test

Ran 3 tests containing 4 assertions.
0 failures, 0 errors.
Subprocess failed

```

**Comment by miikka** [comment]
Hi! I tried to reproduce this using `centos:7.4.1708` Docker image. I installed the same versions of Leiningen and PhantomJS and followed your script. I don't get `Subprocess failed`, but I don't get the fontconfig warning either.

Could you check out the suggestions in https://github.com/ariya/phantomjs/issues/13433 and see if they help?

**Comment by 0xbase12** [comment]
Hello miikka, thanks to your answer, `export LC_ALL=en_US.UTF-8` fixed the issue.
