### ISSUE TITLE
Karma: custom file patterns for static resource loading

### ISSUE THREAD

**Issue by bliksemman** [bensu/doo#165]
Karma supports the option to point to static files. This can be used to host static resources from the webserver. This is useful way to load test data. Especially for applications that have no server backend.

An example of this would be:

`{"pattern" "test/**/*.ogg" "watched" false  "included" false "served" true "nocache" true}`

My use-case is to use this to load audio files. What would be the way to add support for this in doo? As far as I can see there are two options:

1. Add an extra config flag specifically for this feature
2. Allow loading of a custom Karma file

Option 2 might require a template language or having merging logic. I could work on a pull request but I am unsure as to what the best approach would be. Which if these options would be preferred (or is there another option)?

**Comment by miikka** [comment]
In #108, there's a suggestion of adding a way to pass arbitrary configuration options to Karma via the `:karma {:config {}}` option. Would that work?

**Comment by miikka** [comment]
That's a fair point, although I think that if the configs would be merged with [meta-merge](https://github.com/weavejester/meta-merge) (the same way as Leiningen profiles are), that'd be probably good enough.

I feel a bit uneasy about the templating approach, but I don't yet have have proper arguments against it. You're right, though, it's a very flexible approach. I need to think about it a bit more.

**Comment by miikka** [comment]
With version 0.1.9, if you do this:

```clojure
{:doo {:karma {:config {"files" [{"pattern": "test/**/*.ogg", "watched": false,
   "included": false, "served": true, "nocache": true}]}}}}
```

the `ogg` pattern is appended to the files configured by Doo. Would this solve your problem?

**Comment by bliksemman** [comment]
Thanks, this almost works. I made a small fix for the files section (needs to be a vector for the merging to properly work): https://github.com/bensu/doo/pull/173

**Comment by bliksemman** [comment]
I am closing this ticket because this now works.

**Comment by awkay** [comment]
Any chance we can get a release on this fix. I need it as well, and 0.1.9 ^:prepend fails because of the lack of a vector.
