### ISSUE TITLE
Usage via boot-cljs-test broken during changes to add Karma

### ISSUE THREAD

**Issue by crisptrutski** [bensu/doo#18]
Haven't tried to understand the error yet, or looked at your changes, but have verified that still working after #13 and broken on master.

Here's the stracktrace:

```
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No value supplied for key: null
    data
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No value supplied for key: null
     java.lang.IllegalArgumentException: No value supplied for key: null
                                         ...
                       clojure.core/hash-map            core.clj:  371
                                         ...
                          clojure.core/apply            core.clj:  630
               clojure.java.shell/parse-args           shell.clj:   50
                       clojure.java.shell/sh           shell.clj:  112
                                         ...
                          clojure.core/apply            core.clj:  630
                         doo.core/run-script            core.clj:  150
```

Am just calling doo like so: `(doo.core/run-script :rhino) "/super/long/boot/temp/path.js"`

**Comment by crisptrutski** [comment]
Ah, I see the method signature has changed :)

**Comment by bensu** [comment]
I'm sorry! I didn't deploy it to clojars since it is still wip. I guess I should *start* by bumpling the version.

**Comment by bensu** [comment]
Also, I'm not sure about how to handle that signature, hard to say how much should `doo.core/run-script` know about compiler options.

**Comment by bensu** [comment]
`01.5-SNAPSHOT` on master. The last change to `0.1.5` will have a corresponding stable release.

**Comment by crisptrutski** [comment]
Awesome thanks! 

Perhaps push out 0.1.4 with the pre karma version too? That's tied to my last boot-cljs-test version.

Hadn't thought about `run-script` needing more compiler options, but will look closer at your changes and think about the ideal API

**Comment by bensu** [comment]
`0.1.4` deployed to clojars from the branch `release.1.4`. The last commit is your PR.

In the future, I'll work on a feature/version branch, so that master reflects the last deployed artifact.

**Comment by crisptrutski** [comment]
Much appreciated :ghost:
