### ISSUE TITLE
Making lein-cljsbuild optional

### ISSUE THREAD

**Issue by cldwalker** [bensu/doo#19]
Would you be open to supporting non lein-cljsbuild workflows that use `:doo` or `:cljsbuild` in project.clj? Considering that cljs.test comes with clojurescript, this library could be a go to for the bare metal workflow dnolen is encouraging with mies. Depending on if we use `:doo` or `:cljsbuild`, we would have to detect the presence of lein-cljsbuild. As for reimplementing cljsbuild fns, `config` seems trivial to implement if we assume the latest builds format. `subproject` is a little involved but not much inlining.
I'm happy to take a stab if desired

**Comment by bensu** [comment]
@cldwalker you should join the slack channel, #clojurescript. We've been discussing this issue to death with @bhauman and @shaunlebron. `lein-cljsbuild` is on its way out, and `doo` only uses it to get some things from the config, and without the user. Changes are coming but it is still not clear *how*.

For refence look at [lein-cljs](https://github.com/bensu/lein-cljs).

**Comment by cldwalker** [comment]
lein-cljs is great as a minimal replacement of lein-cljsbuild but even that plugin seems at odds with David's workflow. While I can see the advantage of coupling doo to lein-cljs for user-friendliness, I'm not sure if it's worth losing users who use David's workflow.

**Comment by bensu** [comment]
Users who use the scripts workflow will be more comfortable using the library part of `doo`. Maybe your concerns can be address by properly documenting `doo.core/run-script` and how to write scripts that leverage it. `lein-doo` can't cater to David's workflow by definition :)

**Comment by bensu** [comment]
I'm closing this issue since it is being covered by `doo.core/run-script`. If you have a specific script that is causing problems, please open another issue and we'll see what's missing feature or documentation wise.
