### ISSUE TITLE
Require the test namespaces as part of the doo-tests macro

### ISSUE THREAD

**Issue by lvh** [bensu/doo#3]
Right now, you have to manually require namespaces before you can pass them to the doo-tests macro. It seems like the doo-tests macro could produce a `(require ~@namespaces)` forms?

**Comment by bensu** [comment]
Seems like nice sugar to have. I'll check if there are any caveats with the approach before adding it.

**Comment by bensu** [comment]
Requiring namespaces outside of the `ns` form is not supported by the compiler.
