### ISSUE TITLE
Release 0.1.5

### ISSUE THREAD

**Issue by danielcompton** [bensu/doo#37]
@bensu would it be possible to release 0.1.5? I understand that it's under a SNAPSHOT because the behaviour is subject to change, but it does raise the risk of breaking existing code, e.g. #36. The Karma test runner could still be marked as experimental and subject to breaking changes, but at least it would be a stable point for those that need to use it. 

I know that I can specify a particular SNAPSHOT version to pin dependencies, but I don't know how widely spread this knowledge is and if others are doing it too.

Just a thought.

**Comment by bensu** [comment]
I'll do it when #36 is closed.

**Comment by bensu** [comment]
`0.1.5` released.
