### ISSUE TITLE
Provide the ability to add arbitrary Karma plugins

### ISSUE THREAD

**Issue by danielcompton** [bensu/doo#43]
I'd like to be able to add [karma-junit-reporter](https://github.com/karma-runner/karma-junit-reporter) to my karma.conf.js file. I can imagine in the long run that lots of people will all want to install their own Karma plugins. There are a few ways to accomodate this:
- Add a command to allow people to generate a `karma.conf.js` file to disk and then they can add their plugins, configuration, e.t.c. to that static file. The problem with this approach is regenerating it when things change, and it getting out of date.
- Allow extra arguments to be passed on the command line. Some Karma plugins can be activated by this method, though they probably still need some config provided
- Allow people to provide extra config which gets merged into the map used for creating `karma.conf.js`. This would be somewhat similar to how Leiningen merges profiles into the main project config.

This presupposes that the Karma plugins will be able to understand the output of doo tests, I'm not sure if that's the case.

Relates to #34.

**Comment by bensu** [comment]
Tricky. If doo every supports something like this, it will probably follow the last option, a merged in config. To see if this is needed, we should first explore/solve #34 either through docs or features and after that think about plugins in general.

**Comment by cdorrat** [comment]
Pull request [108](https://github.com/bensu/doo/pull/108) hasn't been reviewed yet but it adds the ability to add arbitrary config to karma.conf.js by adding it to project.clj. I'm currently using it to define custom lanchers and change the karma server host name without any issues.

**Comment by miikka** [comment]
#108 has been merged and it's now possible to pass custom Karma configuration. See [README](https://github.com/bensu/doo#custom-karma-configuration). This feature is included in `[lein-doo "0.1.9"]`.
