### ISSUE TITLE
Enable passing a regex to doo-all-tests

### ISSUE THREAD

**Issue by arichiardi** [bensu/doo#48]
Mimicking `run-all-tests`.

I can take care of it, it should be so easy to do :+1:

**Comment by bensu** [comment]
Go for it!

Make sure to check they are regex objects and not strings. I have some ideas for what to do with strings, and is not just transforming to the equivalent regex. So something like `(run-all-tests #"youregex")` and not `(run-all-tests "a-string")`.

**Comment by arichiardi** [comment]
Can you share your ideas for strings, maybe I can take a stab at it :)

**Comment by bensu** [comment]
Closed by #50
