### ISSUE TITLE
Add CI testing for doo

### ISSUE THREAD

**Issue by danielcompton** [bensu/doo#54]
It would be good to have CI to run tests against doo to prevent regressions. One way to approach it would be to run tests which are multiple projects * all optimisations * all runners * Windows and Linux. Travis has a good test matrix capability to support this.

**Comment by bensu** [comment]
Did you try the `example/script/test-all.sh` script? Do you think that Travis can run something like that?

**Comment by danielcompton** [comment]
The test-all script will fail if any single command fails. I've opened #55 with an approach using CircleCI.

**Comment by bensu** [comment]
@danielcompton #55 is awesome, thank you. I read this issue before it.

**Comment by bensu** [comment]
Fixed by #55
