### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by danielcompton** [bensu/doo#63]
There have been quite a few changes since the last SNAPSHOT release. Would it be possible to release a new version?

An issue with having long running snapshots is that when code changes in a SNAPSHOT it can break running tests. Normally you would deal with that by pinning to specific snapshot versions, like `0.1.5-20150918...`. However I don't think it is possible (it's certainly not easy), to pin a particular `lein-doo` plugin SNAPSHOT and make it use a particular pinned version of the `doo` library it depends on, as `lein-doo` just specifies a dependency on `0.1.6-SNAPSHOT`.

Would it make more sense to release `alpha` or `beta` versions when you don't want to release full versions?

**Comment by bensu** [comment]
I'm just waiting to merge Nashorn support and then I'll release. If it doesn't happen in the next couple of days, I'll release an alpha as you suggested.

**Comment by bensu** [comment]
I just pushed `[0.1.6-rc.1]`, please give it a go. I'll release `0.1.6` when a couple of people have tested `rc.1`.

**Comment by danielcompton** [comment]
I've updated and it ran fine. I forgot to install `karma-cli` on our CI machine, but other than that it was a smooth upgrade.

**Comment by bensu** [comment]
Great thanks!

**Comment by bensu** [comment]
`0.1.6` is out!

**Comment by crisptrutski** [comment]
Nice! :elephant:
