### ISSUE TITLE
No output from slimerjs runner

### ISSUE THREAD

**Issue by crisptrutski** [bensu/doo#7]
Despite the workaround for `https://github.com/laurentj/slimerjs/issues/223` of using `window.callPhantom`, I'm not seeing any test results for the `slimer` option.

Have tried this with two projects, and in both cases only the `slimer` option is silent.

Any ideas?

**Comment by bensu** [comment]
One options is that Slimer is not terminating (maybe due to faulty async tests). The output is flushed out when Slimer terminates. If it never does, you won't see anything. 

I'll happily look at a minimal case and debug from there.

**Comment by crisptrutski** [comment]
Turns out my installation of slimerjs had rotted - even `slimerjs --version` was mute. Reinstalled fixed, and working great with doo now :)
