### ISSUE TITLE
Expose the running runner?

### ISSUE THREAD

**Issue by arichiardi** [bensu/doo#70]
Hi @bensu,

I wanted to ask you if there is a way to know which runner is currently executed in order to pass it to my tests. For instance to execute node-specific configuration as test fixture.

If this is not exposed, I could work on doing it and submit a PR ;)

**Comment by danielcompton** [comment]
Another option for node specific code would be to include it in your build confit section, say something like `:source-paths ["src" "test" "platform/node"]`.

**Comment by bensu** [comment]
@arichiardi I'm not sure I understand. Do you want to know inside the cljs test what is currently running? If so, you can look at https://github.com/bensu/maxwell

You can do this:

```clj
(ns some.tests
  (:require [cljs.test :refer :all]
                [maxwell.spy :as spy]))

(deftest runner-dependent-test
  (cond 
    (spy/chrome?) (test-in-chrome)
    (spy/safari?) (test-in-safari)
    :else (test-everywhere-else)))
```

If that doesn't solve your problem, please explain further so we can figure it out.

**Comment by bensu** [comment]
I think @arohner was doing something similar.

**Comment by arichiardi** [comment]
Basically I have tests here: https://github.com/ScalaConsultants/replumb/blob/master/test/cljs/replumb/repl_test.cljs

I would like to change the target options (at runtime) based on the build I'd, if it's nodejs I would like to pass `:target :nodejs` to my `read-eval-call`.

**Comment by bensu** [comment]
If that is all you want then you can use `doo.runner/node?` from inside your tests. You can see it's implementation [here](https://github.com/bensu/doo/blob/master/library/src/doo/runner.cljs#L18)

**Comment by arichiardi** [comment]
Oh great I did not see it, sorry about this, I even skimmed through the source...but too quickly it seems :)

**Comment by bensu** [comment]
No problem! I'm closing this then.
