### ISSUE TITLE
Add explicit "runner not installed" errors

### ISSUE THREAD

**Issue by crisptrutski** [bensu/doo#8]
As you demonstrate in https://github.com/bensu/doo#setting-up-environments, there are simple checks to test whether underlying runners are installed.

For a user-friendlier experience, perhaps these exact checks should be performed by the application, so that friendlier error messages (or even installation instructions) can be shown.

Motivation for this comes from when a default runner is bundled downstream (eg. from a lein template https://github.com/martinklepsch/tenzing/pull/28), and the end user may not be familiar with what the command means.

**Comment by crisptrutski** [comment]
`rhino -help` seems to have return code `1`, so going with `echo "" > rhino` instead for that case.

**Comment by bensu** [comment]
I'm all for the check if `doo` is a transitive dependency but the checks offered in the README are not the way. The startup time of Rhino and Slimer are substantial. If we can figure out a clean way to check after the fact if the runner was not installed, this would be great. 

Maybe a regex against the console output to check for "command not found", but that would be very OS dependent.

**Comment by crisptrutski** [comment]
Maybe just detecting that the process exited without running the entry point function? Simple and agnostic

**Comment by bensu** [comment]
An error code of 127 [seems to be universal](http://www.tldp.org/LDP/abs/html/exitcodes.html) for command not found:

```sh
> slimerrrr
slimerrrr: command not found
> echo $?
127
```

**Comment by bensu** [comment]
The fix was deployed under `[0.1.3-SNAPSHOT]`
