### ISSUE TITLE
Test failure on stderr print

### ISSUE THREAD

**Issue by moea** [bensu/doo#87]
Similar to #83, but not involving the quit-on-print behaviour.  I'm running into a situation on Node with this line, I guess:

https://github.com/bensu/doo/blob/master/library/src/doo/core.clj#L264

Where log messages cause the test to fail after completion, despite a successful exit code.  Given that process exit codes aren't broken on Node, it would seem reasonable to disable this check there, at least - and maybe any other platforms which can signal failure w/ exit codes.  More than happy to submit a PR for the Node change, if you think that's reasonable.

**Comment by bensu** [comment]
The check is only necessary as long as #39 exists. Instead of checking for Node, it would be better only to check for PhantomJS/Slimer as you proposed. If you have the time, give it a go. (Otherwise I'll get to it) Thanks!
