### ISSUE TITLE
Schemas not being validated

### ISSUE THREAD

**Issue by scttnlsn** [bensu/doo#89]
I'm using [prismatic/schema](https://github.com/Prismatic/schema) and validating the schemas using `cljs-test` fixtures:

```clj
(use-fixtures :once schema.test/validate-schemas)
```

The fixture is being used (i.e. schemas are validated) when I run the tests via a REPL (i.e. `(run-tests 'my.namespace)`) but not when running the tests with Doo.

**Comment by bensu** [comment]
Thanks for the report! The error might be related to [this comment](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/test.cljs#L138). Do you have an example repo? It might speed things up.

**Comment by bensu** [comment]
This is an upstream issue: I've isolated the error to `cljs.test/use-fixtures` [here](https://github.com/bensu/cljs-fixtures-bug)  without using `doo`. We will probably handle this in the compiler.

**Comment by bensu** [comment]
I was unable to reproduce the issue in this [example repo](https://github.com/bensu/cljs-fixtures-bug). Can you provide a project that displays the issue? (You could use the example repo as a starting point).

**Comment by scttnlsn** [comment]
Thanks for looking into this!  I'm also unable to reproduce the issue in your example repo.  I'll try and narrow down the differences with my existing project (where this is not working) and report back here.

**Comment by scttnlsn** [comment]
My mistake.  I was just passing the wrong namespaces to `doo-tests` (test namespace w/ invalid schemas was not even being run).  Really sorry to waste your time here.

**Comment by bensu** [comment]
No problem!
